#Serveur web non créé dans ce repo pour hoster les challenges 
version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - data-volume:/app/public


  # Automatisation is key
  automatisationiskey:
    build: .\CTF_challenges\ChiffrementRépété
    volumes:
      - data-volume:/app/data


  # XOR with 64
  xorwith64:
    build: .\CTF_challenges\XORwith64
    volumes:
      - data-volume:/app/data

  # Login Page 1 
  loginpage:
    build:
      context: .\CTF_challenges\LoginPage
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./CTF_challenges/LoginPage/index.html:/usr/share/nginx/html/index.html
      - ./CTF_challenges/LoginPage/p455w0rD.html:/usr/share/nginx/html/p455w0rD.html

  # Login Page 2
  loginpage2:
    build:
      context: .\CTF_challenges\LoginPage
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates

  #Check The Log
  checkthelog:
      build:
        context: .\CTF_challenges\SYSLOG_CTF
        dockerfile: Dockerfile
      ports:
        - 4444:22

#Stop Brute Force
  ssh_victim:
      build: .\CTF_challenges\STOP-BRUTEFORCE\ssh_victim
      privileged: true
      networks:
        ctf_network:
          ipv4_address: 192.168.10.2
      cap_add:
        - NET_ADMIN
        - NET_RAW
        - SYS_MODULE
      ports:
        - "2222:22"
#Stop Brute Force
  attacker:
    build: .\CTF_challenges\STOP-BRUTEFORCE\Attacker 
    networks:
      ctf_network:
        ipv4_address: 192.168.10.169
    depends_on:
      - ssh_victim
#Stop Brute Force
networks:
  ctf_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
volumes:
  data-volume:
